### ISSUE TITLE
Yongchao Fu | 付永超

### ISSUE THREAD

**Issue by s0521** [s0521/s0521.github.io#12]
https://s0521.github.io/

**Comment by YUKI-yuki1222** [comment]
偶遇付老师主页，支持一下！

**Comment by dongsar** [comment]
太棒的網頁跟資訊 從沒想過有中文關於phoenix NLME這麼好的介紹
我個人也用phoenix做population PK正在做PhD的題目
最近正苦惱AUC的處理剛好看到您的介紹豁然開朗 想請教個延伸問題 關於AUC在某個時間區段內或某個目標濃度之下的計算方式 我使用如下PML code可運行但不確定是否正確
AUC last= deriv(AUC = C) 如老師所述

AUC t0-12 :  deriv(AUC = (t>0)*(t<12)*C)
AUC below 20 :	deriv(AUCbelow20 = (C>=20? 20:C))
AUC below 20 within t0-12 :	deriv(AUCbelow20 = (t>0)*(t<12)*(C>=20? 20:C))

目的是想計算PTA ( probability of target attainment)
即有多少比例的AUC落於MIC之上
或是有其他更好的應用Phoenix或R來計算PTA的方式還請您指點迷津!
非常感謝!

**Comment by s0521** [comment]
[dongsar](https://github.com/dongsar)你好，
### 问题1：时间区段内的AUC如何计算
解答：不能直接计算时间区段内AUC，应仅计算AUClast，在输出表格时输出time=12时的AUClast即为AUC0~12（此在[PML中AUC的计算方法](https://s0521.github.io/cn/2019/11/pml%E4%B8%ADauc%E7%9A%84%E8%AE%A1%E7%AE%97%E6%96%B9%E6%B3%95/)的一文中提到过）；
### 问题2：目的是想計算PTA ( probability of target attainment)
解答：你的目的2似乎描述不清，你似乎不能准确识别与区分“AUC below”与“PTA ( probability of target attainment)”概念。
比如：
> AUC是面积，C是浓度，无法比较

> AUCbelow计算的是具体那部分的面积呢：
> - 在低于20时，计算(20-C)的面积，高于20时按20计算然后相加？还是任取其一？
> - 或者是计算低于20时，计算C的面积，高于20时按0计算然后相加？还是任取其一？
> - 再或者是计算高于C高于20时持续时间的占比？

> 计算达成概率需基于群体模型进行蒙特卡洛模拟，计算出每个个体的值，之后在模型之外使用描述性统计对象描述性统计得到分位数，以此分位数替代概率。

虽然不知你的具体计算目标是什么，但给出浓度高于20时的AUC面积计算公式吧，有了此面积，你可以与AUClast组合计算出你想要的其他面积：deriv(AUC_above=C>20?C:0)

祝好

**Comment by dongsar** [comment]
老師您好
關於從Phoenix的輸出報告inter-subject variability我的理解如下 但無法確定是否正確想請老師指教

phoneix model output中有Omega與OmegaStder兩個表格
以V為例 paper中通常呈現為
-----------------------------------------------------------------
                         Estimate          RSE%
omegaV          即Omega        OmegaStder / Omega
-----------------------------------------------------------------

我的問題是
一般所謂inter-subject variability指的是RSE%的部分?
當加入適當的Covariate後照理說inter-subject variability被部分解釋所以會下降
那這下降的數值應表現在RSE%下降 ? 抑或是Omega estimate本身下降呢?
麻煩老師解惑
感謝!

**Comment by s0521** [comment]
> @dongsar
> 我的問題是
> 一般所謂inter-subject variability指的是RSE%的部分?
> 當加入適當的Covariate後照理說inter-subject variability被部分解釋所以會下降
> 那這下降的數值應表現在RSE%下降 ? 抑或是Omega estimate本身下降呢?
> 麻煩老師解惑
> 感謝!
> 

@dongsar你好，

①一般所謂inter-subject variability指“Estimate”→Omega表格中的值→ω<sup>2</sup>

②那這下降的數值應表現在RSE%下降 ?指Omega Estimate”→Omega表格中的值→ω<sup>2</sup>下降。

祝好
