### ISSUE TITLE
关于药物动力学学科的思考 - Yongchao Fu | 付永超

### ISSUE THREAD

**Issue by s0521** [s0521/s0521.github.io#6]
https://s0521.github.io/cn/2019/05/%E5%85%B3%E4%BA%8E%E8%8D%AF%E7%89%A9%E5%8A%A8%E5%8A%9B%E5%AD%A6%E5%AD%A6%E7%A7%91%E7%9A%84%E6%80%9D%E8%80%83/

**Comment by shihao94** [comment]
写的简单易懂，感谢分享！不知道有没有对优化方法书籍的推荐？谢谢！

**Comment by s0521** [comment]
> @shihao94
> 写的简单易懂，感谢分享！不知道有没有对优化方法书籍的推荐？谢谢！

想要怎样的关于优化的书籍，中文的英文的？
中文：
《最优化计算方法》作者蒋金山，
《非线性优化计算方法》作者袁亚湘，
中文的都是通用的优化方法书籍不是专门面向药学专业的。

英文：
Pharmacokinetic-Pharmacodynamic-Modeling-and-Simulation，作者Peter L. Bonate，
这本是专门面向药学专业的书籍。

**Comment by StevenQPMx** [comment]
哈哈，之前一直有关注您家的公众号，原来大部分内容都有您的参与呀。最近在丁香园上看到了您发布了PK&PD Data Analysis: Concepts and Applications, ed. 5。请问能借阅吗？
