### ISSUE TITLE
大家有啥想看的疾病数学模型 - Yongchao Fu | 付永超

### ISSUE THREAD

**Issue by s0521** [s0521/s0521.github.io#63]
https://s0521.github.io/cn/2020/07/%E5%A4%A7%E5%AE%B6%E6%9C%89%E5%95%A5%E6%83%B3%E7%9C%8B%E7%9A%84%E7%96%BE%E7%97%85%E6%95%B0%E5%AD%A6%E6%A8%A1%E5%9E%8B/

**Comment by tata9898** [comment]
大佬，我想看抗病毒药物的PD模型怎么弄
