### ISSUE TITLE
肿瘤增长 抑制数学模型 - Yongchao Fu | 付永超

### ISSUE THREAD

**Issue by s0521** [s0521/s0521.github.io#64]
https://s0521.github.io/cn/2020/08/%E8%82%BF%E7%98%A4%E5%A2%9E%E9%95%BF-%E6%8A%91%E5%88%B6%E6%95%B0%E5%AD%A6%E6%A8%A1%E5%9E%8B/

**Comment by tata9898** [comment]
大佬 求代码

**Comment by s0521** [comment]
文中包含的有代码，你可自己对照文中代码的图片自己还原出对应的代码。
