### ISSUE TITLE
做BE分析时高概率遇到的几大疑惑现象 - Yongchao Fu | 付永超

### ISSUE THREAD

**Issue by s0521** [s0521/s0521.github.io#65]
https://s0521.github.io/cn/2020/08/%E5%81%9Abe%E5%88%86%E6%9E%90%E6%97%B6%E9%AB%98%E6%A6%82%E7%8E%87%E9%81%87%E5%88%B0%E7%9A%84%E5%87%A0%E5%A4%A7%E7%96%91%E6%83%91%E7%8E%B0%E8%B1%A1/

**Comment by robot-zzz** [comment]
您好，不知道您还是否维护着这个网站。我在帮我老板分析生物等效性时发现方差分析的受试者（sequence*subject）和周期（period）显著性（P value）都小于0.05。这说明了什么呢？造成这种情况的原因是什么呢？
是不是实验时对于受试者或者第一第二周期的处理有差异？以至于没有形成一个正态分布？
